---
- name: Playbook para agregar usuario ansible
  hosts: # todos los nodos a administrar 
  tasks:
    - name: asegurarse que existe el grupo ansible
      group:
        name: ansible
        state: present

    - name: Permitir passwordless sudo para el grupo ansible
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: "%ansible ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"
        
    - name: add user ansible
      user:
        name: "ansible"
        group: ansible
        home: /home/ansible/
        shell: /bin/bash
        state: present
        password: # encrypt passwd

    - name: Set ssh keybase login
      authorized_key:
        user: ansible
        key: "{{ item }}"
      with_file:
        - /home/ansible/.ssh/id_rsa.pub
...
