---
- name: JBoss eap migration
  hosts: all
  become: true
  serial: 1
  gather_facts: false
  vars:
    current_eap_home: "/opt/jboss-eap-7.1"
    new_eap_home: "/opt/jboss-eap-7.2"
    eap_service: "jboss-eap"

  tasks:
    - name: copy and extract jboss eap zip file to remote machine
      unarchive:
        src: jboss-eap-7.2.0.zip
        dest: /opt/
        owner: jboss
        group: jboss

    - name: migrate configuration
      command: ./jboss-server-migration.sh -s "{{ current_eap_home }}" -i false
      args:
        chdir: "{{ new_eap_home }}/bin"
      register: resultado

    # resultado de la migracion
    - debug: 
        msg: "{{resultado.stdout}}"

    - name: update jboss eap service daemon 
      lineinfile:
        path: /etc/default/jboss-eap.conf
        regexp: 'JBOSS_HOME='
        line: JBOSS_HOME={{ new_eap_home }}

    - name: restart jboss-eap service
      service:
        name: "{{ eap_service }}"
        state: restarted


    # workaround error de permisos en algunos folder al iniciar por primera vez, (data,log, content)
    - name: stop jboss-eap service
      service:
        name: "{{ eap_service }}"
        state: stopped 

    - name: change permissions
      shell: chown -R jboss:jboss {{ new_eap_home }}

    - name: start jboss-eap service
      service: 
        name: "{{ eap_service }}"
        state: started
